# redis.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruoyi-redis
  namespace: ruoyi-infra
spec:
  selector:
    matchLabels:
      app: ruoyi-redis
  template:
    metadata:
      labels:
        app: ruoyi-redis
    spec:
      containers:
        - name: ruoyi-redis:6.0
          image: redis:latest
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: ruoyi-redis
  namespace: ruoyi-infra
spec:
  ports:
    - port: 6379
  selector:
    app: ruoyi-redis